### ISSUE TITLE
关于样式修改的问题

### ISSUE THREAD

**Issue by 6zc** [le5le-com/topology-vue-js#1]
这绘图工具太牛逼了！
不过，我想请问一下，界面的样式可以自己修改吗？比如将常用图形直接放到顶部工具栏这样子？

**Comment by mathieulin** [comment]
> 这绘图工具太牛逼了！ 不过，我想请问一下，界面的样式可以自己修改吗？比如将常用图形直接放到顶部工具栏这样子？
> 
> 没事了没事了！我学会了！

老哥怎么弄呢
